ci: add final collection steps for build matrix
This step can be set in the rules for merging. Otherwise, one would have to
include every build in the matrix.

diff --git a/.github/workflows/elisp-tests.yml b/.github/workflows/elisp-tests.yml
--- a/.github/workflows/elisp-tests.yml
+++ b/.github/workflows/elisp-tests.yml
@@ -32,3 +32,13 @@ jobs:
       - uses: nixbuild/nix-quick-install-action@v29
       - name: Run Tests
         run: nix run --system ${{ matrix.system }} -L ".#checks.${{ matrix.system }}.${{ matrix.target }}"
+
+  build-done:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if any previous steps failed
+        if: ${{ needs.build.result == 'failure' }}
+        run: |
+          echo "One or more jobs in the matrix failed."
+          exit 1
